name: "AI Algorithm Mentor"
description: "algorithm code review using LLM"
author: "choam2426"
inputs:
  GITHUB_TOKEN:
    description: "GitHub personal access token for repository access"
    required: true
  LLM_PROVIDER:
    description: "AI model provider to use for code review (openai, google, anthropic)"
    required: true
    default: "google"
  MODEL_NAME:
    description: "Model name to use for code review (e.g., gpt-5-nano, gpt-5.1, gemini-2.5-flash, gemini-3-pro-preview, claude-haiku-4-5, claude-sonnet-4-5)"
    required: false
    default: "gemini-3-pro-preview"
  OPENAI_API_KEY:
    description: "OpenAI API key (required when LLM_PROVIDER is 'openai')"
    required: false
  GEMINI_API_KEY:
    description: "Google Gemini API key (required when LLM_PROVIDER is 'google')"
    required: false
  ANTHROPIC_API_KEY:
    description: "Anthropic Claude API key (required when LLM_PROVIDER is 'anthropic')"
    required: false
  REVIEW_LANGUAGE:
    description: "Language for code review comments (e.g., english, korean, german)"
    required: false
    default: "korean"
  WEBCRAWLER_API_KEY:
    description: "WebCrawlerAPI key for scraping BOJ problems (https://webcrawlerapi.com/)"
    required: true

runs:
  using: "docker"
  image: "docker://choam2426/ai_algorithm_mentor:v5"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    LLM_PROVIDER: ${{ inputs.LLM_PROVIDER }}
    MODEL_NAME: ${{ inputs.MODEL_NAME }}
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
    ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
    REVIEW_LANGUAGE: ${{ inputs.REVIEW_LANGUAGE }}
    WEBCRAWLER_API_KEY: ${{ inputs.WEBCRAWLER_API_KEY }}
branding:
  icon: "check-circle"
  color: "blue"
