name: 🤖 AI Algorithm Mentor

on:
  push:
    branches: [ main ]

jobs:
  algorithm-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: choam2426/AI-Algorithm-Mentor@v5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_PROVIDER: openai              # openai, google, anthropic
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}      # required when LLM_PROVIDER is 'google'
          # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}  # required when LLM_PROVIDER is 'anthropic'
          REVIEW_LANGUAGE: korean           # korean, english, etc.. (optional)
